In [2]:
import pandas as pd

df = pd.read_csv("../data/raw/nyc_sales_property_raw.csv")

print(df.shape)

(845607, 29)

C:\Users\capul\AppData\Local\Temp\ipykernel_6388\1788780298.py:3: DtypeWarning: Columns (11: RESIDENTIAL UNITS, 12: COMMERCIAL UNITS, 13: TOTAL UNITS) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/raw/nyc_sales_property_raw.csv")

In [3]:
df.shape

(845607, 29)

In [4]:
df.head()

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AS OF FINAL ROLL,BLOCK,LOT,EASE-MENT,BUILDING CLASS AS OF FINAL ROLL,ADDRESS,APARTMENT NUMBER,...,SALE PRICE,SALE DATE,Latitude,Longitude,Community Board,Council District,BIN,BBL,Census Tract 2020,Neighborhood Tabulation Area (NTA) (2020)
0,1,CHINATOWN,47 CONDO NON-BUSINESS STORAGE,4,172,1490,NaN,RS,"50 FRANKLIN STREET, S9B",S9B,...,"$1,590,000",06/21/2019,40.716951,-74.002500,101.0,1.0,1088222.0,1.001728e+09,31.0,MN0102
1,1,EAST VILLAGE,10 COOPS - ELEVATOR APARTMENTS,2,461,24,NaN,D4,"232 EAST 6TH STREET, 6D",NaN,...,"$515,000",06/11/2019,40.727669,-73.989201,103.0,2.0,1006622.0,1.004610e+09,38.0,MN0303
2,1,FASHION,21 OFFICE BUILDINGS,4,779,23,NaN,O6,227 WEST 29TH STREET,NaN,...,$0,05/03/2019,40.748263,-73.993857,105.0,3.0,1014284.0,1.007790e+09,95.0,MN0501
3,1,FASHION,13 CONDOS - ELEVATOR APARTMENTS,2,841,1044,NaN,R4,"16 WEST 40TH STREET, 26A",26A,...,"$5,203,258",03/11/2019,40.752505,-73.982574,105.0,4.0,1090404.0,1.008418e+09,84.0,MN0502
4,1,EAST VILLAGE,10 COOPS - ELEVATOR APARTMENTS,2,431,31,NaN,D4,"141 EAST THIRD STREET, 2E",NaN,...,"$975,000",12/27/2019,40.723793,-73.985602,103.0,2.0,1005762.0,1.004310e+09,32.0,MN0303

In [5]:
df.dtypes

BOROUGH                                        int64
NEIGHBORHOOD                                     str
BUILDING CLASS CATEGORY                          str
TAX CLASS AS OF FINAL ROLL                       str
BLOCK                                          int64
LOT                                            int64
EASE-MENT                                    float64
BUILDING CLASS AS OF FINAL ROLL                  str
ADDRESS                                          str
APARTMENT NUMBER                                 str
ZIP CODE                                     float64
RESIDENTIAL UNITS                             object
COMMERCIAL UNITS                              object
TOTAL UNITS                                   object
LAND SQUARE FEET                                 str
GROSS SQUARE FEET                                str
YEAR BUILT                                   float64
TAX CLASS AT TIME OF SALE                      int64
BUILDING CLASS AT TIME OF SALE                   str
SALE PRICE                                       str
SALE DATE                                        str
Latitude                                     float64
Longitude                                    float64
Community Board                              float64
Council District                             float64
BIN                                          float64
BBL                                          float64
Census Tract 2020                            float64
Neighborhood Tabulation Area (NTA) (2020)        str
dtype: object

In [6]:
df.columns.tolist()

['BOROUGH',
 'NEIGHBORHOOD',
 'BUILDING CLASS CATEGORY',
 'TAX CLASS AS OF FINAL ROLL',
 'BLOCK',
 'LOT',
 'EASE-MENT',
 'BUILDING CLASS AS OF FINAL ROLL',
 'ADDRESS',
 'APARTMENT NUMBER',
 'ZIP CODE',
 'RESIDENTIAL UNITS',
 'COMMERCIAL UNITS',
 'TOTAL UNITS',
 'LAND SQUARE FEET',
 'GROSS SQUARE FEET',
 'YEAR BUILT',
 'TAX CLASS AT TIME OF SALE',
 'BUILDING CLASS AT TIME OF SALE',
 'SALE PRICE',
 'SALE DATE',
 'Latitude',
 'Longitude',
 'Community Board',
 'Council District',
 'BIN',
 'BBL',
 'Census Tract 2020',
 'Neighborhood Tabulation Area (NTA) (2020)']

In [7]:
df.isna().sum()

BOROUGH                                           0
NEIGHBORHOOD                                      0
BUILDING CLASS CATEGORY                           0
TAX CLASS AS OF FINAL ROLL                     4183
BLOCK                                             0
LOT                                               0
EASE-MENT                                    845607
BUILDING CLASS AS OF FINAL ROLL                4183
ADDRESS                                           0
APARTMENT NUMBER                             636936
ZIP CODE                                         67
RESIDENTIAL UNITS                            133666
COMMERCIAL UNITS                             211747
TOTAL UNITS                                  119362
LAND SQUARE FEET                             226053
GROSS SQUARE FEET                            226048
YEAR BUILT                                    39410
TAX CLASS AT TIME OF SALE                         0
BUILDING CLASS AT TIME OF SALE                    0
SALE PRICE                                        0
SALE DATE                                         0
Latitude                                      23278
Longitude                                     23278
Community Board                               23277
Council District                              23277
BIN                                           26479
BBL                                           26479
Census Tract 2020                             23024
Neighborhood Tabulation Area (NTA) (2020)     23024
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(3351)

In [9]:
duplicates = df[df.duplicated(keep=False)]

duplicates.head(10)

,BOROUGH,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AS OF FINAL ROLL,BLOCK,LOT,EASE-MENT,BUILDING CLASS AS OF FINAL ROLL,ADDRESS,APARTMENT NUMBER,...,SALE PRICE,SALE DATE,Latitude,Longitude,Community Board,Council District,BIN,BBL,Census Tract 2020,Neighborhood Tabulation Area (NTA) (2020)
36,1,CIVIC CENTER,10 COOPS - ELEVATOR APARTMENTS,2,161,1,NaN,D4,"180 PARK ROW, 8B",NaN,...,$0,06/17/2019,40.713193,-73.999917,103.0,1.0,1077438.0,1.001610e+09,2902.0,MN0301
155,1,CIVIC CENTER,10 COOPS - ELEVATOR APARTMENTS,2,161,1,NaN,D4,"180 PARK ROW, 8B",NaN,...,$0,06/17/2019,40.713193,-73.999917,103.0,1.0,1077438.0,1.001610e+09,2902.0,MN0301
327,1,CLINTON,10 COOPS - ELEVATOR APARTMENTS,2,1066,37,NaN,D4,"408 WEST 57TH STREET, 7I",NaN,...,$0,03/19/2019,40.768159,-73.986307,104.0,3.0,1026870.0,1.010660e+09,139.0,MN0402
350,1,CIVIC CENTER,10 COOPS - ELEVATOR APARTMENTS,2,161,1,NaN,D4,"180 PARK ROW, 8B",NaN,...,$0,06/17/2019,40.713193,-73.999917,103.0,1.0,1077438.0,1.001610e+09,2902.0,MN0301
477,1,CLINTON,10 COOPS - ELEVATOR APARTMENTS,2,1066,37,NaN,D4,"408 WEST 57TH STREET, 7I",NaN,...,$0,03/19/2019,40.768159,-73.986307,104.0,3.0,1026870.0,1.010660e+09,139.0,MN0402
1078,1,GRAMERCY,10 COOPS - ELEVATOR APARTMENTS,2,904,50,NaN,D4,"200 EAST 24TH STREET, 710",NaN,...,$0,08/08/2019,40.739459,-73.982603,106.0,2.0,1019782.0,1.009040e+09,64.0,MN0602
1387,1,GRAMERCY,13 CONDOS - ELEVATOR APARTMENTS,2,870,1433,NaN,R4,"1 IRVING PLACE, U16E",U16E,...,$0,11/29/2019,40.734072,-73.988713,105.0,2.0,1083247.0,1.008708e+09,50.0,MN0602
1483,1,GRAMERCY,10 COOPS - ELEVATOR APARTMENTS,2,904,50,NaN,D4,"200 EAST 24TH STREET, 710",NaN,...,$0,08/08/2019,40.739459,-73.982603,106.0,2.0,1019782.0,1.009040e+09,64.0,MN0602
1757,1,GRAMERCY,13 CONDOS - ELEVATOR APARTMENTS,2,870,1433,NaN,R4,"1 IRVING PLACE, U16E",U16E,...,$0,11/29/2019,40.734072,-73.988713,105.0,2.0,1083247.0,1.008708e+09,50.0,MN0602
2149,1,GREENWICH VILLAGE-WEST,10 COOPS - ELEVATOR APARTMENTS,2,636,22,NaN,D4,"165 CHRISTOPHER STREET, 1I",NaN,...,$0,05/13/2019,40.732621,-74.008822,102.0,3.0,1011980.0,1.006360e+09,75.0,MN0203

In [10]:
duplicates.shape

(5786, 29)

## Data Profiling

The raw NYC property sales dataset contains 845,607 records and 29 columns.

The initial profiling identified several data quality issues:

1. 3,351 exact duplicate records
2. Missing values in several analytical fields, including 'TOTAL UNITS', 'RESIDENTIAL UNITS', 'COMMERCIAL UNITS', 'LAND SQUARE FEET', 'GROSS SQUARE FEET', and 'YEAR BUILT'
3. Incorrect data types where numeric fields were imported as text and will require type conversion before analysis
4. The 'EASE-MENT' column contains NaN
5. 'SALE PRICE' contains valid $0 ownership transfers that will require separate tratment from the cash-based sales analysis

These issues are to be resolved during the cleaning stages while preserving valid records and documenting the reasoning behind each of the transformations.